export default {
  ITEMS_FETCH: 'items/ITEMS_FETCH',
  ITEMS_FETCH_SUCCESS: 'items/ITEMS_FETCH_SUCCESS',
  ITEMS_FETCH_FAIL: 'items/ITEMS_FETCH_FAIL',
  ITEMS_FETCH_RESET: 'items/ITEMS_FETCH_RESET',
};
